<?php

declare(strict_types=1);

namespace PoP\UserStateAccessControl\Conditional\CacheControl\TypeResolverDecorators;

use PoP\UserStateAccessControl\TypeResolverDecorators\ValidateUserLoggedInForDirectivesTypeResolverDecoratorTrait;

class ValidateUserLoggedInForDirectivesPrivateSchemaTypeResolverDecorator extends AbstractNoCacheConfigurableAccessControlForDirectivesInPrivateSchemaTypeResolverDecorator
{
    use ValidateUserLoggedInForDirectivesTypeResolverDecoratorTrait;
}
