<?php
namespace PoP\UserStateAccessControl\Conditional\CacheControl\TypeResolverDecorators;

use PoP\UserStateAccessControl\TypeResolverDecorators\ValidateUserNotLoggedInForDirectivesTypeResolverDecoratorTrait;

class ValidateUserNotLoggedInForDirectivesPrivateSchemaTypeResolverDecorator extends AbstractValidateBasedOnUserStateForDirectivesPrivateSchemaTypeResolverDecorator
{
    use ValidateUserNotLoggedInForDirectivesTypeResolverDecoratorTrait;
}
