<?php
namespace PoP\UserStateAccessControl\TypeResolverDecorators;

use PoP\UserStateAccessControl\TypeResolverDecorators\ValidateUserLoggedInForFieldsTypeResolverDecoratorTrait;

class ValidateUserLoggedInForFieldsPublicSchemaTypeResolverDecorator extends AbstractValidateBasedOnUserStateForFieldsPublicSchemaTypeResolverDecorator
{
    use ValidateUserLoggedInForFieldsTypeResolverDecoratorTrait;
}
